### ISSUE TITLE
管理页面按新建文章，尝试保存时就出现错误

### ISSUE THREAD

**Issue by ghost** [fantasticit/wipi#33]
管理页面按新建文章，尝试保存时就出现错误。而且我是用dev模式的，不明白为什么还会去读dist里面的file。谢谢了
```
[Nest] 6716   - 02/23/2021, 12:32:06 AM   [ExceptionsHandler] Cannot read property 'role' of null +24561ms
TypeError: Cannot read property 'role' of null
    at roles.some.role (E:\wipi\packages\server\dist\modules\auth\roles.guard.js:33:58)
    at Array.some (<anonymous>)
    at RolesGuard.canActivate (E:\wipi\packages\server\dist\modules\auth\roles.guard.js:33:31)
    at GuardsConsumer.tryActivate (E:\wipi\packages\server\node_modules\@nestjs\core\guards\guards-consumer.js:14:34)
    at canActivateFn (E:\wipi\packages\server\node_modules\@nestjs\core\router\router-execution-context.js:132:59)
    at E:\wipi\packages\server\node_modules\@nestjs\core\router\router-execution-context.js:41:37
    at E:\wipi\packages\server\node_modules\@nestjs\core\router\router-proxy.js:8:23
    at Layer.handle [as handle_request] (E:\wipi\packages\server\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\wipi\packages\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\wipi\packages\server\node_modules\express\lib\router\route.js:112:3)

```

**Comment by fantasticit** [comment]
你本地是怎么启动的？`npm run dev` 吗？

**Comment by ghost** [comment]
对啊。我也尝试过用pm2 那个启动，结果是有其他的问题

**Comment by fantasticit** [comment]
你截个图吧，数据库正常启动了吗？
