### ISSUE TITLE
启动项目后，访问 client 和 admin 报错，表都没进行初始化操作。

### ISSUE THREAD

**Issue by yang-shuting** [fantasticit/wipi#35]
[Nest] 8795   - 2021/02/27 下午4:50:31   [ExceptionsHandler] ER_NO_SUCH_TABLE: Table 'wipi.article' doesn't exist +186516ms
QueryFailedError: ER_NO_SUCH_TABLE: Table 'wipi.article' doesn't exist
    at new QueryFailedError (/Volumes/DOC/github/wipi/packages/server/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/Volumes/DOC/github/wipi/packages/server/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
    at Query.<anonymous> (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Volumes/DOC/github/wipi/packages/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)

**Comment by fantasticit** [comment]
你好，修了，麻烦拉一下代码。

**Comment by yang-shuting** [comment]
> 你好，修了，麻烦拉一下代码。

辛苦啦 🙏
